  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Portfolio"
  weight = 200
  identifier = "portfolio"
  url = "/portfolio/"  

  [[main]]
  name = "Resume"
  identifier = "resume"
  weight = 300
  url = "/docs/resume.pdf"

  [[main]]
  name = "Blog"
  weight = 400
  identifier = "blog"
  url = "https://blog.simonwu.tech"

#  [[main]]
#  name = "About"
#  weight = 400
#  identifier = "about"
#  url = "/about/"

#  [[main]]
#  name = "Accomplishments"
#  weight = 500
#  identifier = "accomplishments"

#  [[main]]
#  name = "Awards"
#  weight = 510
#  identifier = "awards"
#  url = "/awards/"
#  parent = "accomplishments"  

#  [[main]]
#  name = "Certifications"
#  weight = 520
#  identifier = "certifications"
#  url = "/certifications/"
#  parent = "accomplishments"

#  [[main]]
#  name = "Contact"
#  weight = 600
#  identifier = "contact"
#  url = "/contact/"

#  [[footer]]
#  name = "imprint"
#  weight = 1
#  identifier = "imprint"
#  url = "/imprint/"